#! /bin/zsh

. ${0:P:h:h}/utils

<"$1" grep -Eo -e 'mul\([[:digit:]]{1,3},[[:digit:]]{1,3}\)|do\(\)|don'\''t\(\)' |
  awk -F'[(),]' -v go=1 -v sum=0 '
    /don/ { go=0; next; }
    /do/ { go=1; next; }
    go { sum += $2 * $3 }
    END { print sum }
  '
